# Generated by Django 4.0.3 on 2022-03-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(max_length=200, verbose_name='Этап')),
                ('data', models.CharField(max_length=50, verbose_name='Дата')),
                ('position', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программа',
            },
        ),
        migrations.CreateModel(
            name='Сomitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.TextField(verbose_name='Должности')),
                ('type', models.CharField(max_length=200, verbose_name='Комитет')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Комитет',
                'verbose_name_plural': 'Комитет',
            },
        ),
    ]
