# Generated by Django 4.0.3 on 2022-03-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=200, verbose_name='Ученое звание')),
                ('theme', models.CharField(max_length=200, verbose_name='Тема научного доклада')),
                ('type', models.CharField(max_length=200, verbose_name='Физ. лицо')),
                ('format', models.CharField(max_length=50, verbose_name='Роль')),
                ('company', models.CharField(max_length=50, verbose_name='Организация')),
                ('status', models.CharField(max_length=50, verbose_name='Должность')),
                ('email', models.CharField(max_length=50, verbose_name='e-mail')),
                ('tel', models.CharField(max_length=50, verbose_name='Телефон')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('discription', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
