# Generated by Django 4.0.3 on 2022-03-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Вид образования'),
        ),
    ]
