# Generated by Django 4.0.3 on 2022-03-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('sec', 'Среднее'), ('high', 'Высшее')], max_length=5, verbose_name='Вид образования'),
        ),
    ]
