# Generated by Django 4.0.3 on 2022-03-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_client_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('sec', 'Юридическое лицо'), ('high', 'Физическое лицо')], max_length=5, verbose_name='Вид образования'),
        ),
    ]
